server:
  port: 8082


#是否激活 swagger true or false
swagger:
  enable: true

##默认密码为空
redis:
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      jedis:
        pool:
          #连接池最大连接数（使用负值表示没有限制）
          max-active: 100
          # 连接池中的最小空闲连接
          max-idle: 10
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 100000
      # 连接超时时间（毫秒）
      timeout: 5000
      #默认是索引为0的数据库
      database: 0

soa.home.manager.host: http://127.0.0.1:8081

#用户信息 需要排除的地址
userinfo.excludedPages: /css/,/fonts/,/img/,/business/,/favicon.ico,/js/,/lib/,/error/,/logout,/temp,/erp/,/manager/login
